---
name: autofix.ci
on:
  pull_request:
    paths:
      - 'src/lib/posts/**/*.md'
  workflow_dispatch:
jobs:
  textlint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup mise
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0
        with:
          install: true
          log_level: 'debug'
      - name: Install pnpm # <-- Add this block
        run: npm install -g pnpm
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache .npm directory
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run textlint
        # textlint の終了コードを強制0にする
        run: npx textlint --fix src/lib/posts/**/*.md | true
        shell: bash {0}
      - name: Autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
